### ISSUE TITLE
Translate game language to english

### ISSUE THREAD

**Issue by romavini** [mdcdxcvi/Explorer#4]
I think that changing the language (or adding language options) will facilitate access to the project.

**Comment by kushagra-shukla** [comment]
Hey I think I can do it using properties files. Assign this issue to me. I do not know much but I found this article [Internationalilzation](https://docs.oracle.com/javase/tutorial/i18n/intro/steps.html). I think it should be easy this way and more generic and leaves room for multiple language support. It can be added by just adding properties files for that language without any need to change the source code. You can then raise issues for which ever language support you want or others want.

**Comment by romavini** [comment]
Excelente, @kushagra-shukla!

**Comment by kushagra-shukla** [comment]
I have completed the work. [**See the result**](https://imgur.com/SWki9FR). 
I have made a pull request for the same. #11
